### ISSUE TITLE
customTheme: False should follow the theming like in light-brightness-preset-row

### ISSUE THREAD

**Issue by clarsonJWU** [finity69x2/fan-control-entity-row#10]
![Capture](https://user-images.githubusercontent.com/28867715/73551286-1cb6d400-4414-11ea-870a-7bac2d3447ad.PNG)

Both the fan control and light control in the snapshot are set to "customTheme: False". Would like for fan-control to follow the same default values as the light-control plugin to be consistent

**Comment by finity69x2** [comment]
@clarsonJWU

for me it does...

![ex](https://user-images.githubusercontent.com/32221243/73849592-354e3200-47f8-11ea-9b25-02fe3c9eb926.gif)

Have you updated to the latest fan-control-row version?

**Comment by clarsonJWU** [comment]
Hmmm, might be something with caching on my end. I had it installed since before HACS. I reinstalled via HACS and removed the old reference about a month ago.

I just uninstalled via HACS, and do not have the files in either www\community or the original directory of www\custom_ui. However, if I leave the resource in my ui-lovelace.yaml file it still displays. I even restarted home assistant and it still shows the card without having the plugin installed.

**Comment by clarsonJWU** [comment]
I am running the latest 1.2 version on home assistant 104.3

I cleared my browser cache and was able to get a clean install, but still had the same issue. I compared the js file for both and noticed a difference in the backgroun-color: var() references. The working light-brightness-preset-row references --switch-checked-button-color and --switch-unchecked-button-color. The fan-control-entity-row js references --switch-checked-color and --switch-unchecked-color.

Deleting the gz file and then updating the fan js to use --switch-checked-button-color and --switch-unchecked-button-color resolves the issue for me.

**Comment by finity69x2** [comment]
@clarsonJWU 

thanks for the heads up. I just checked in mine that are installed and they are as you say (different - not sure how I missed that).

Strange that mine worked fine but your didn't.

Now I'm not sure which is the "correct" way. I'll have to check the HA frontend docs and figure out which style they used for the default.

I'll update one or the other and let you know which is correct.

**Comment by finity69x2** [comment]
@clarsonJWU 

After looking thru the HA styles it seems that the fan control row style is correct but there is a missing style option being used that prevents the "--switch-unchecked-button-color" from being rendered correctly. 

So that said I'm going to change the light brightness plugin to match the fan control row plugin. that way I hope everything will stay working if they decide to fix the missing element.

So you'll probably have to update both to get them matching. I've got the new release up in my repo now and it should hit HACS soon.
