### ISSUE TITLE
Support for changing order of turn_on and set_speed

### ISSUE THREAD

**Issue by tomlevels** [finity69x2/fan-control-entity-row#12]
For my fan, the current setting of speed is not working. In your code, first a set_speed is sent, and then a turn_on. This is not working for my fan: it first needs the turn_on and then the set_speed. Is it possible to add an option for this?

**Comment by finity69x2** [comment]
@tomlevels 

I've got the code switched around but I don't necessarily want to do a full release with it until I know that it will work for you (and others...)

can you test the new code for me with your setup and let me know if it works?

I put the updated code into the dev branch if you want to install that and test it.

**Comment by tomlevels** [comment]
I tried your new code and it works fine for my fan. Of course I cannot be sure it works for everybody, but if it does not, maybe it could be made in to an option in the configuration

**Comment by finity69x2** [comment]
@tomlevels 

Ok thanks for testing it for me.

I've tested it on my two versions of iFan's and it works for both of mine as well.
