### ISSUE TITLE
fan-control-entity-row.js:219:1 Uncaught SyntaxError: Unexpected token '}'

### ISSUE THREAD

**Issue by biga888** [finity69x2/fan-control-entity-row#14]
I am seeing this in the logs with the latest update.

/community_plugin/fan-control-entity-row/fan-control-entity-row.js:219:1 Uncaught SyntaxError: Unexpected token '}'

**Comment by biga888** [comment]
not sure if I did this right, but made the changes and created a pr  to work with 106.0

**Comment by finity69x2** [comment]
sorry that was a code typo, on my part on making some changes. it's fixed now.

as far the PR I don't know if it would make any difference. My install works now without those changes. I'll leave it open for now and see if it might be necessary in the future as everything is still (always...) in flux right now.

Thanks for the help tho.

**Comment by biga888** [comment]
Thanks, I did see the typo fix, but I have not seen any other changes for at least a month? 
I thought it was the typo at first, but there was mention of how the plugin work and the includes that were not needed anymore. Is there a new commit that I am not seeing?

**Comment by finity69x2** [comment]
I'm not sure what you mean by "but there was mention of how the plugin work and the includes that were not needed anymore."

I haven't made any changes to the code since the typo fix an it still works for me on V107.7.

Is yours not working?
