### ISSUE TITLE
docs gone wild

### ISSUE THREAD

**Issue by pruchai** [finity69x2/fan-control-entity-row#16]
There are 3 different places that tell you how to install this plugin and all 3 have different paths and plugin types.....

In this repo
![Screen Shot 2020-03-02 at 8 27 27 PM](https://user-images.githubusercontent.com/2467628/75743120-bc41dd80-5cc4-11ea-931f-4bde0ada4af9.png)

In the community post
![Screen Shot 2020-03-02 at 8 27 55 PM](https://user-images.githubusercontent.com/2467628/75743132-cbc12680-5cc4-11ea-9c79-d4e2cad787a6.png)

in HACS
![Screen Shot 2020-03-02 at 8 27 01 PM](https://user-images.githubusercontent.com/2467628/75743138-d11e7100-5cc4-11ea-9f48-2abdf2b659a1.png)

what gives? can we get a single consistent source of truth?

**Comment by finity69x2** [comment]
The thing is they are all "true".

it all depends on how you decide to install the plugin.

if you install it via HACS the follow those instructions.

if you install it manually then you have to place it somewhere in your /www/ folder. the exact path is up to you.

I have mine installed in the a /www/lovelace/ directory. Hence why I wrote ""modifying the directory for the location that you created the component" in the community post and "updating the location to where you placed the above file" in the instructions. It's up to you exactl;y where you place it as long as it's somewhere under the /config/www/ directory.

As far the /www/ vs /local/ difference that is the way that HA references files in the /www/ directory.

the physical location is "/config/www/" but it is referenced by "/local/".

None of this is a documentation problem per se. it's just an idiosyncrasy of how HA/HACS//etc. works.
