### ISSUE TITLE
Typo in Options table

### ISSUE THREAD

**Issue by mycortex** [finity69x2/fan-control-entity-row#18]
Not a big deal, but I troubled a bit with this before I noticed it.

![image](https://user-images.githubusercontent.com/48593936/78140500-69c22100-742a-11ea-8b8b-1774d39b20dc.png)

Just to let you know :)

**Comment by finity69x2** [comment]
Thanks for the heads up.

Fixed! (Along with another one you didn't catch...  ;) )
