### ISSUE TITLE
Off state not working 

### ISSUE THREAD

**Issue by boojew** [finity69x2/fan-control-entity-row#20]
EDIT: seems I misunderstood how sendStateWithSpeed was supporsed to work. That is not the issue...

I have a MQTT based fan that, for some reason, will not turn off when using v1.5 of this plugin w/ hass 0.110. Works w/ my 3 other Insteon based fans. From what I can see the service call fan.turn_off doesnt seem to be sufficient, but rather the fan expects fan.set_speed set to off..

**Comment by boojew** [comment]
Playing around a bit, I am wondering if calling the speed is a better approach? Not sure. Perhaps there should be a variable. I essentially just changed line 208 to 
`	 
this.hass.callService('fan', 'set_speed', {entity_id: this._config.entity, speed: speed}); 
`

And it solved my issue and also worked for my other fans. What do you think?

**Comment by finity69x2** [comment]
which mqtt based fan is it?

if you go to the services tab and select the fan.turn_off service and put in your entity_id for your fan does the fan turn off when you call the service?

**Comment by boojew** [comment]
It’s a zigbee fan through zigbee2mqtt. I’ve tried calling the service, but it does not stop.

**Comment by finity69x2** [comment]
Sorry for all the questions but I'm trying to fully understand the situation before making changes...

If you use a regular entity row for the fan controls and click on the toggle switch for the fan are you able turn the fan off from there?

![Inkedex4](https://user-images.githubusercontent.com/32221243/83927646-8c8af180-a75b-11ea-9dbd-5d565987d1be.gif)

and if you can what does the speed shown in the drop down menu below that say?

**Comment by boojew** [comment]
Yea, it doesnt work.. Perhaps this is actually more of a Zigbee2Mqtt issue in the way the fan domain is implemented
Before turning off
![image](https://user-images.githubusercontent.com/1015566/83974236-dee22480-a8b9-11ea-91f5-c6ad3e03d80f.png)
After turning off
![image](https://user-images.githubusercontent.com/1015566/83974234-db4e9d80-a8b9-11ea-8ce2-e0d0458da094.png)

Setting the speed as off does work

**Comment by finity69x2** [comment]
Yeah I think it is a zigbee2mqtt issue.

Does that fan happen to be a Hampton Bay fan controller?

I just bought one of those a week ago and it gives me the exact same "speed list".

I have it connected to my system using the ZHA integration and it works the same as the rest of my fans do and works fine with my control row config.

![ex1](https://user-images.githubusercontent.com/32221243/84072201-d3b3f500-a99c-11ea-891a-31cd9cb3499d.gif)

**Comment by boojew** [comment]
Yea, that's the fan!

**Comment by finity69x2** [comment]
then it has to be a problem with zigbee2mqtt since mine is working perfectly using the control row  with it connected via ZHA.
