### ISSUE TITLE
Custom background color since 1.8

### ISSUE THREAD

**Issue by Mace404** [finity69x2/fan-control-entity-row#28]
Since version 1.8 the customIsOffSpdColor setting has no effect anymore.

Version 1.8 and 1.9:
![image](https://user-images.githubusercontent.com/41652357/90387637-d4e15c80-e086-11ea-9562-2684ae84098b.png)

Version 1.7:
![image](https://user-images.githubusercontent.com/41652357/90387668-e0348800-e086-11ea-83f3-d4e76fd0faaf.png)

Using the following card settings:
```
              - entity: fan.dyson_pure_cooltm
                name: Dyson
                type: 'custom:fan-control-entity-row'
                sendStateWithSpeed: true
                customTheme: true
                customIsOffColor: var(--primary-color)
                customIsOffSpdColor: var(--secondary-background-color)
                customIsOnHiColor: var(--primary-color)
                customIsOnLowColor: var(--primary-color)
                customIsOnMedColor: var(--primary-color)
                state_color: true
```

**Comment by finity69x2** [comment]
Right that was a breaking change.

Please see the new updated readme for the new config option.

specifically it is now called "buttonInactiveColor".

The other custom color config options have changed as well. I wanted to make all of my custom plugins be consistent so I changed some of the config options.

Sorry about that.
