### ISSUE TITLE
Off Button does nothing

### ISSUE THREAD

**Issue by wotelljm** [finity69x2/fan-control-entity-row#29]
The off button no longer works.  I am using a BOND but the "off" event does work with scripts or sending the event manually.

**Comment by raz0rf0x** [comment]
I noticed an issue with that in relation to using the BOND fan control integration. I brought it up in [this](https://github.com/home-assistant/core/issues/39349) issue.

I believe it is related to this part of the .js:
```
	setSpeed(e) {
		const speed = e.currentTarget.getAttribute('name');
		if( speed == 'off' ){
			this.hass.callService('fan', 'turn_off', {entity_id: this._config.entity});
			this.hass.callService('fan', 'set_speed', {entity_id: this._config.entity, speed: speed});
		} ...
```
By commenting out the `this.hass.callService('fan', 'set_speed', {entity_id: this._config.entity, speed: speed});` line I was able to get the "off" command to work.

I would suggest a feature request to be able to turn off "set_speed" with off for integrations that don't like that.

**Comment by raz0rf0x** [comment]
I have submitted a PR: 
https://github.com/finity69x2/fan-control-entity-row/pull/30

**Comment by raz0rf0x** [comment]
@wotelljm
I just tested the https://github.com/home-assistant/core/pull/39488 fix and it resolves this problem even without the PR I submitted above. Hopefully it'll be in the next HA update.

The code maintainer for the BOND integration has updated it to correctly respond to a fan speed of "off". This seems to allow this custom component to work normally.

**Comment by finity69x2** [comment]
Then I assume the PR is no longer needed?

**Comment by raz0rf0x** [comment]
> Then I assume the PR is no longer needed?

Not to fix this issue, no. I resolved it with the BOND integration maintainer  If there isn't a use case for anything else it can be ignored.

**Comment by finity69x2** [comment]
Ok, thanks for the info. I'll close it.

**Comment by wotelljm** [comment]
Correct.  I had the old implementation of the Bond integration installed.
It was installed manually through the custom components and manually
downloaded files.  After removing this and installing the new integration
through the "integrations" mechanism it is working now.
