### ISSUE TITLE
No fan speed when HA restarts

### ISSUE THREAD

**Issue by phreaq** [finity69x2/fan-control-entity-row#31]
I'm using this fan controller, and have it showing in lovelace. However, if a fan is on, and HA reboots, when it comes back up, the interface shows that the fan is off, even though it's still on.

How can I make it so the speed shows after reboots?

**Comment by finity69x2** [comment]
It depends on what integration you are using for the fan.

What does the state of the fan show after reboot in the developers tools-> states page? Does it show as on or off?

**Comment by phreaq** [comment]
thanks for the reply, and sorry for the delay.

It shows 'off' when I do a restart,so I guess I need to look into my tasmota settings... although the console does return this:

stat/LivingRoom_Fan/RESULT = {"PowerRetain":"ON"}
