### ISSUE TITLE
Depreciated Java

### ISSUE THREAD

**Issue by ThirteenTX** [finity69x2/fan-control-entity-row#34]
Since the latest update I have noticed that the add-on now says it is depreciated in the Configuration>Lovelace>Resources section. It also fails to load half of the time which I think is related to that as I have other depreciated front end add-ons that are doing the same. I have to refresh a few times for it to display the card now. Not sure if there are any tweaks I can do on my end so I figured I would reach out here. Let me know if you need more info.

**Comment by finity69x2** [comment]
I'm sorry but I'm not really sure what you mean.

I'm still using the plugin and I'm on the latest version of HA and I don't see anything like that.

Is there any way you can clarify or post screen shots of what you are seeing?

**Comment by ThirteenTX** [comment]
This was just a bug in the last version and it appears to be corrected in the latest version. I forgot to come back and update this but  it's working without issue now. Thanks for getting back to me.
