### ISSUE TITLE
Feature request: 2-speed fan

### ISSUE THREAD

**Issue by NateLogan** [finity69x2/fan-control-entity-row#35]
Hello,
I have several bathroom fans with only two speeds. Would it be possible to hide/disable third speed in config?

**Comment by finity69x2** [comment]
That isn't possible right now and frankly I doubt it will ever be implemented by me.

So far I've had requests for 4 speed, 5 speed 6 speed and 10 speed fan controls. And now a request for a 2 speed fan control. At some point I have to say 'no' so unfortunately I'm saying that I really likely won't make any others and just stick with the three speed variety.

If I can find a way to do it easily I might implement it so for now I'm closing this. But if I do it I'll re-open and post it here and in the forum.

**Comment by finity69x2** [comment]
Actually I just figured out an easy way to do this so I'll re-open this.

**Comment by finity69x2** [comment]
I've released a new version with this request. I hid the medium speed button so the other two speeds must still be low and high for it to work properly.

**Comment by NateLogan** [comment]
Thank you, it works like a charm 👍
