### ISSUE TITLE
Missing Auto Mode on some fans

### ISSUE THREAD

**Issue by TRusselo** [finity69x2/fan-control-entity-row#38]
My Air purifier has fan speed attributes, but also has a mode attribute.
![image](https://user-images.githubusercontent.com/1154815/102744007-ee850000-4315-11eb-99fe-e06598035afe.png)

If you manually select a speed, mode sets to 'manual'.
the purifier has an auto button. sets mode to Auto. Speed becomes null

![image](https://user-images.githubusercontent.com/1154815/102744240-96023280-4316-11eb-94ee-3cc957178a88.png)

If you could add option:

auto_button : true  (default false)
Enables an Auto button, the Auto button sets mode attribute to auto,

**Comment by TRusselo** [comment]
Actually adding Air Quality Level might be another good add.

![image](https://user-images.githubusercontent.com/1154815/102744972-4cb2e280-4318-11eb-8fcf-61185ea9eb7b.png)

I'm better with microsoft paint than code.
this picture is a forgery. including the Auto button

**Comment by finity69x2** [comment]
Unfortunately, I don't have any fans that have the auto functionality so I don't have any way to know how the code works for those.

And TBH, it's not really a feature I would want to include anyway.

I've had many feature requests for very specific functions that wouldn't be useful to the vast majority of people and adding those to the code would make this pretty overwhelming.

And the air quality display is definitely out. I think you can already do that using built-in functions on a second row by creating a sensor from the attribute or I think you can use custom lovelace cards to add the info to the secondary-info field.

**Comment by TRusselo** [comment]
the logic is not hard, it can be understood from the 2 screen shots.

When attribute mode is set to auto, fan speed becomes null.  (unit sets its own speed dependent on air quality attribute)
When fan speed attribute is set to anything, the machine sets mode attribute back to manual (nothing to do).

Really it only comes down to adding a single Auto button, when pressed it sets mode attribute to auto, button lights up, if speed is null, low, med, high, should not be highlighted, only auto.  Also if mode state changes to auto by other means, light up button.

If i knew python it would be done already, and you'd have a pull request.

But i understand if you don't want to include this.  Im sure you have other things to do.
