### ISSUE TITLE
Home Assistant Mobile App doesn't display entity

### ISSUE THREAD

**Issue by msfoote** [finity69x2/fan-control-entity-row#40]
The element is terrific. I'm able to see it on my dashboards both on desktop and Mobile browsers.  When I try to view it on the Home Assistant Android app I see errors.

Custom element doesn't exist: fan-control-entity-row.
entity: fan.fan_switch_family_room_level
type: 'custom:fan-control-entity-row'
name: Family Room
customTheme: false
reverseButtons: true

Apologies if this is the wrong way to post this.

**Comment by finity69x2** [comment]
If it works in the other locations then there is nothing wrong with the plugin itself.

It's likely a cache issue.

Can you clear the cache on the phone and force the page to update? Or maybe there is a way to refresh Lovelace from within the app itself?

**Comment by msfoote** [comment]
Thank you for closing this.  I can't say specifically that it was cache related but that makes sense.  I was able to refresh the app after a day or two and it started showing.  Thank you for the great work and apologies for not responding sooner.
