### ISSUE TITLE
Fan service calls changing

### ISSUE THREAD

**Issue by raz0rf0x** [finity69x2/fan-control-entity-row#42]
Heads up:
I'm on the dev build right now and I get this when I use this lovelace addon. 
`[homeassistant.components.fan] fan.set_speed is deprecated, use fan.set_percentage or fan.set_preset_mode instead.`
Explanations of the new methods are [here in the dev docs](https://developers.home-assistant.io/docs/core/entity/fan/).
I don't know when this method is going away entirely, but this is coming at some point.

**Comment by sumasage** [comment]
this change has took effect for the lastest HA update.  Will you update this to work with the new version?

**Comment by mdeluca1992** [comment]
Would love to be able to tell each button what percentage it should be setting the fan at. After the most recent update the low button makes my fan medium, the medium is medium still, and high is high.

**Comment by sumasage** [comment]
fix can be found here https://community.home-assistant.io/t/2021-03-and-tasmotized-sonoff-ifan03-lots-of-errors-in-log-and-fan-unavailable/286780/10

nothing is wrong with the add on just need to add quotation mark to:

    payload_available: "Online"
    payload_not_available: "Offline"
    speeds:
      - "off"
      - "low"
      - "medium"
      - "high"

**Comment by scotty1395** [comment]
I still get the error message after adding quotes.

`fan.set_speed is deprecated, use fan.set_percentage or fan.set_preset_mode instead.`

**Comment by finity69x2** [comment]
Yeah, that is from the new fan control scheme.

If you want to try it out you can install my newly created "fan-percent-button-row" available from my github or thru HACS.

It hopefully will solve the issues above.

And since this should be handled by the other plugin I'm going to close this now.
