### ISSUE TITLE
Error with HA > V2021.3.X 

### ISSUE THREAD

**Issue by sjthespian** [finity69x2/fan-control-entity-row#44]
With the new fan percentage system, this plugin is now throwing an error:
  `Failed to call service fan/set_speed. invalid literal for int() with base 10: 'low'`

Is there a way to get this working with the new fan model, or do I need to replace it with fan-percent-button-row for all of my fans?

**Comment by finity69x2** [comment]
If you have switched your fans over to use the new fan model and are actually using percents (and not modes) then you should use the percent row.

I am in the process of making a new control row to use the modes as well but I'm still trying to figure out how those work.

I'm really not happy that they aren't going to make this backwards compatible with people who use the old speed method of control.

**Comment by broyuken** [comment]
what is the percent row? I don't see anything in the docs.

**Comment by finity69x2** [comment]
sorry, it's a completely new plugin.

find it here:

https://github.com/finity69x2/fan-percent-button-row

**Comment by broyuken** [comment]
Ah thank you.
