### ISSUE TITLE
Button resizing setting does not work

### ISSUE THREAD

**Issue by roofuskit** [finity69x2/fan-control-entity-row#45]
Nothing seems to work, no matter the number of forced refreshes. All other settings seem to take effect.

**Comment by finity69x2** [comment]
it's working fine for me.

Could you please post the config for the button row that isn't working?

**Comment by roofuskit** [comment]
You can close this. Sorry I had forgotten about it. At some point recently
it started working. I'm guessing it was fixed by restarting home assistant
as that's the only thing I think has changed since trying to increase the
button size.
