### ISSUE TITLE
Card doesn't work in HA 2021.4.4.

### ISSUE THREAD

**Issue by hqsone** [finity69x2/fan-control-entity-row#46]
Hello! Card doesn't work in HA 2021.4.4.
Because set_speed is deprecated now

P.S. Card is great!

**Comment by finity69x2** [comment]
Right.

You need to update to using the new "fan percent button row" plugin or the soon to be new fan preset mode plugin depending on which way you have updated your fan to work with the new updates.

the fan percent button row is active but not available in HACS yet so you'll have to install it manually in the meantime.

I'll try to get the preset button row done and active pretty soon. Check the forum thread about my plugins for when it is available. 

https://community.home-assistant.io/t/finally-announcing-my-suite-of-lovelace-plugins/218584
