### ISSUE TITLE
The fan.set_speed service is deprecated

### ISSUE THREAD

**Issue by randellhodges** [finity69x2/fan-control-entity-row#47]
Home Assistant 2021.4.1
Fan Control Entity Row: 2.1

```2021-05-05 12:47:13 WARNING (MainThread) [homeassistant.components.fan] The fan.set_speed service is deprecated, use fan.set_percentage or fan.set_preset_mode instead```

**Comment by finity69x2** [comment]
Yes, for now that's true.

I Have a FR request to leave that functionality intact (see [here](https://community.home-assistant.io/t/add-support-for-named-speed-lists-in-the-fan-integration/306970) to vote for it).

You can either wait to see if that deprecation gets removed or you can switch your fans to use the new fan control models (using percentages or preset modes). I have new plugins for those two that you can find in this repo.
