### ISSUE TITLE
Button - unselected state

### ISSUE THREAD

**Issue by iRanduMi** [finity69x2/fan-control-entity-row#48]
I currently have a BOND controller that sends the fan commands to my fans.  The current plugin works great, however, it can end up 'out of sync' with my actual fan due to users interacting with the physical fan controller itself.  

Example:
1) User utilizes HA to set fan to High Speed
2) User utilizes physical fan controller to set fan to Medium (HA or BOND has no awareness of this)
3) Observe the HA Dashboard continues to display the fan speed at High (Step 1)

Suggestion 1: The ability for the UI to allow a user to select a setting/button but after the selection (ex: High Speed button), the button does not retain a 'IsOn' state but instead just immediately defers back to the 'IsOff' state.  This way, the HA display is not out 'out of sync' with the actual physical state and strictly acts as a controller to send commands but automatically default back to 'IsOff'.

Suggestion 2: Allow the same state to be selected again (MEDIUM is currently selected but allow the user to select MEDIUM again).  I can then simply change the style of the 'IsOn' and 'IsOff' state to be the same.

**Comment by finity69x2** [comment]
suggestion 1 is a no-go.

You definitely need the buttons to reflect the current state that HA thinks the entity is in.

Now as far as #2 I might consider that. I've been asked for that before. I was hesitant to change the "disabled" state of the button but after thinking about it I can't think of any negative effects of allowing a "second-strike" capability on the buttons.

I'll think on it some more tho.

But the best thing for you to do is to figure out why the controller doesn't send an updated state to HA. The controller should always send it's actual state back to HA no matter what the method is that the fans state gets changed.

I would contact the owner of the Bond integration and let them know you are having that issue to see if they can come up with a solution.

**Comment by iRanduMi** [comment]
Thank you for the response/feedback; it's greatly appreciated.  Unfortunately, there is no actual fan controller.  My fan does not have a physical switch on the wall, it only comes with a 433mhz remote which controls the light and the fan speeds (I have 6 of them).  The Bond is simply a device that sends 433mhz signals to the fan.  It doesn't know when a person uses the remote to change the speeds so that's how it gets out of sync.

**Comment by finity69x2** [comment]
Ah, OK. I've had other questions about Bond and I just always assumed it was some other kind of fan controller. Sounds very similar to the Broadlink devices.

I have a fan like that that uses the broadlink for the control and it gets out of synch too. I always just switch the fan speed to a different speed then back to the speed I want. it is kind pf a pain.
