### ISSUE TITLE
Buttons can't be clicked

### ISSUE THREAD

**Issue by chrisgott** [finity69x2/fan-control-entity-row#49]
Using Fan Mode Button Row via Hacs, HA 2021.5.5 on a PI4 Safari 14.1 with and without iOS/MacOS Apps. Fancontroller is a Sonoff iFan02 Tasmotized with 9.3.1

Lovelace:
```
entity: fan.fan_sz
type: 'custom:fan-mode-button-row'
name: Schlafzimmer
reverseButtons: true
```

Problem is, i can't click on all of the 4 Buttons, but no reactions. In the more-info Dialog i can change the speed flawless, can even do so by Servicecalls.

What i did so far:

- Reinstalled Fan Mode Button Row
- Reinstalled Fan Mode Button Row again, with manual cleaning/checking
- Reinstalled HACS
- Installed Fan Mode Button Row
- ...

Of course i restarted HA every time, and cleared cache frequently.

I still donno if it is a Bug or if i did something wrong.

**Comment by finity69x2** [comment]
Does your fan use presets, modes or speeds?

if it doesn't use speeds then this plugin won't work.

look in your log after you click a button to see if it's giving you an error for that service call for the fan.

**Comment by chrisgott** [comment]
the fan itself (a sonoff ifan02) uses steps (off, low, mid, high). ha - as far as i know - translate them to speeds (0,33,66,100%). ha bringts a slider to the infocard, this slider works.

this is in my logs:
`Logger: homeassistant.components.mqtt.fan
Source: components/mqtt/fan.py:676 
Integration: MQTT (documentation, issues) 
First occurred: 9:37:04 (3 occurrences) 
Last logged: 9:37:07

'low'is not a valid preset mode`

**Comment by finity69x2** [comment]
This plugin can't be used with new fan control schema used ion the latest releases of HA.

try using one of the other fan control plugins ("fan percent button row" or "fan mode button row")
