### ISSUE TITLE
Feature request: Support for fans with more than 3 speeds

### ISSUE THREAD

**Issue by Shadowpheonix** [finity69x2/fan-control-entity-row#5]
Any possibility of adding support for fans with more than 3 speeds?

I use the [Hampton Bay Universal Wink Enabled](https://www.homedepot.com/p/Hampton-Bay-Universal-Wink-Enabled-White-Ceiling-Fan-Premier-Remote-Control-99432/206591100) fan controller, which gives my fans the following speed settings...
Low
Medium
Medium-High
High
Comfort Breeze    (FYI, this is a setting where the fan randomly changes speed to simulate a natural breeze)
Off

**Comment by finity69x2** [comment]
I don't plan on making this row support more than a three speed fan.

I know there are variations on this that can be found in threads on the home assistant forums, tho if you want to try those.
