### ISSUE TITLE
Request: Hide off button

### ISSUE THREAD

**Issue by denniswham** [finity69x2/fan-control-entity-row#51]
Hi,

I'm using the fan-control-entity-row for my mechanical ventilation. This is something I can't turn off (which is common in the Netherlands with ITHO devices) so it should be nice to have the option to hide the off. Could this option be added?

**Comment by finity69x2** [comment]
I just published a new release with the ability to hide the Off button.

It should be available in HACS soon.

You can hide the button by setting "hideOff: true" in the card config.

Let me know if there are any issues.
