### ISSUE TITLE
User friendly button view

### ISSUE THREAD

**Issue by davo2022** [finity69x2/fan-control-entity-row#52]
Hi Guys, just signed up and not sure how to use this but. Can you help create a fan card thats user freindly, there only seem to be one card available and its not that user freindly. Im thinking something like the pic attached.

<img width="1156" alt="Screen Shot 2022-02-27 at 4 27 56 pm" src="https://user-images.githubusercontent.com/100506473/155871343-d34cb23c-2389-435e-b4d7-12ad80146fa7.png">

**Comment by finity69x2** [comment]
there is no way you can make anything like that picture using this plugin. 

there are other plugins you can try but I don't know of any that can do what you want directly.

closing this since it's the wrong place to discuss this.
