### ISSUE TITLE
"failed to call service fan/set_speed. Service now found"

### ISSUE THREAD

**Issue by tenisman584** [finity69x2/fan-control-entity-row#53]
Everything was working fine but did recent update of HA core and no longer can I click on "high; med;low". The error is "failed to call service fan/set_speed. Service now found" Any ideas what is broken?

**Comment by czech12** [comment]
I have the same issue.  The problem is that fan.set_speed is no longer a supported service.  It was changed to fan.set_percentage.

I'm not sure I know enough about the code to fix it, but maybe someone else can help.  I will tinker until then.

**Comment by czech12** [comment]
It looks like this was already changed in a different lovelace card.

https://github.com/finity69x2/fan-percent-button-row

**Comment by finity69x2** [comment]
yes, the set_speed service has been deprecated in the recent versions of HA. All fans are now set_percentage instead so you need to update the plug in to the new fan-percent-button-row as linked above.
