### ISSUE TITLE
Fan.set_speed servise is deprecated since 2022.3

### ISSUE THREAD

**Issue by rAdziuB** [finity69x2/fan-control-entity-row#55]
Hi,

I am using your great tool - fan-control-entity-row but lately, it doesn't work properly. Could you update your code and change used service from fan.set_speed to fan.set_percentage? Fan.set_speed is deprecated since 2022.3 

Thanks in advance
Radek

**Comment by finity69x2** [comment]
This card is only designed to work on versions prior to 2021.2.

See the BIG BOLDED warning here:

https://github.com/finity69x2/fan-control-entity-row#this-plugin-is-only-valid-for-use-with-fans-that-still-use-a-speed-list-in-the-fan-configuration-that-fan-control-model-is-deprecated-in-versions-of-home-assistant-20213x-and-later-for-ha-versions-20213x-and-later-use-fan-percent-button-row-or-fan-mode-button-row-if-your-fan-has-been-updated-to-use-the-new-control-methods

IOW, use the fan percent button row from this repo.
