### ISSUE TITLE
Can you add capability for a 4 speed fan.  

### ISSUE THREAD

**Issue by azsoccerpop** [finity69x2/fan-control-entity-row#57]
The Treatlife DS02 and DS03 Fan control has 4 speeds Low, Medium, High, Highest Can you add this as an option?

**Comment by finity69x2** [comment]
This is only available to be used on older versions of HA so I really don't want to put any effort into updating it.

Also I think 4 buttons is the limit of where I think the available space in the row doesn't get too crowded, especially on smaller devices. I've had others ask for up to 6 speeds (or more!) so I have to draw the line somewhere and 4 buttons is the line.

Sorry
