### ISSUE TITLE
Uncaught ReferenceError: Polymer is not defined Ensure that this is NOT used any more.

### ISSUE THREAD

**Issue by acdcnow** [finity69x2/fan-control-entity-row#59]
Running HA 2023.06.2.

Right now this HACS addon will not work an actual releases.
Logger: frontend.js.latest.202306080
Source: components/system_log/__init__.py:257
First occurred: 13:24:36 (3 occurrences)
Last logged: 13:25:59

_### https:*****************/hacsfiles/fan-control-entity-row/fan-control-entity-row.js?hacstag=19166315023:9:28 Uncaught ReferenceError: Polymer is not defined
https:**********frontend_latest/28922-mjI0iZwe1jc.js:2:14655 Uncaught TypeError: Cannot read properties of undefined (reading 'map')_

see dev notes:
https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

Deprecating Polymer
April 4, 2023 · 2 min read

The Home Assistant frontend used to use the [Polymer Library](https://polymer-library.polymer-project.org/3.0/docs/about_30) for her web components. Polymer has since been deprecated and superseded by [Lit](https://lit.dev/).

In the last couple of years, we migrated most of the frontend to Lit, and we only have a few places and dependencies that still use Polymer.

This is good news, as Lit is way faster and lighter than Polymer.

In Home Assistant 2023.4, we finally removed the last piece of Polymer from the entry point of Home Assistant, meaning it is not loaded when the app starts, but only when a component needs it.

For custom cards and panels, we have supplied Polymer on the window object, so it was easier to access and use. But nowadays it is hardly used anymore, and since Home Assistant no longer uses it, it is mainly a big chunk of unused code that is slowing down the loading of Home Assistant.

That's why we decided to remove it.

I**n Home Assistant 2023.5 Polymer will no longer be provided by Home Assistant. If you use Polymer now, we recommend you switch to Lit. If you want to keep using Polymer, you will have to load Polymer yourself.

In Home Assistant 2023.4, we will log a warning every time Polymer is accessed. If you got a log mes**sage, find the custom card, panel, or more info that uses Polymer, and notify the author of this deprecation.

**Comment by finity69x2** [comment]
This card can only be used with older versions of HA for fans that use the deprecated 'set speed' service so I won't be updating it. 

sorry

TBH, I'm confused that you are even seeing this error since you shouldn't be able to use this plugin with the version of HA that created the polymer deprecation error.
