### ISSUE TITLE
Current fan speed not showing with .101 update

### ISSUE THREAD

**Issue by rgabrielson11** [finity69x2/fan-control-entity-row#6]
Current speed is blank but changes speed accordingly when you click on it.  All boxes are blank.

**Comment by egeekial** [comment]
I am having the same issue.

**Comment by rgabrielson11** [comment]
If you change themes it will show up.  So its just an issue with the default theme.

**Comment by andybowser** [comment]
I am having this issue. Has anyone found a fix?

**Comment by rgabrielson11** [comment]
I changed the theme and it seemed to fix. 

---sent from my iPhone

**Comment by rgabrielson11** [comment]
The UI theme. It seems to be ok when on non original. 

---sent from my iPhone

**Comment by egeekial** [comment]
Try my fork: https://github.com/egeekial/fan-control-entity-row. I modified the CSS which seems to work with 0.101 and higher.

**Comment by finity69x2** [comment]
I'm on 104.2 and my fan control using a custom theme is working fine with the current config.

I will look at @egeekial's fork and try to get this one updated.

Thanks.

**Comment by finity69x2** [comment]
I've updated the code to incorporate those changes.
