### ISSUE TITLE
suport zhimi.humidifier.ca1

### ISSUE THREAD

**Issue by MaximSN** [finity69x2/fan-control-entity-row#7]
![2019-12-08 092556](https://user-images.githubusercontent.com/57829001/70385208-45cf6100-199d-11ea-84dc-0eaefc8ff3b2.png)
Please add support for zhimi.humidifier.ca1 
1) add button auto mode;

 2) change the name of "low" mode to "silent"

[fan-control-entity-row.js.txt](https://github.com/finity69x2/fan-control-entity-row/files/3935914/fan-control-entity-row.js.txt)

**Comment by finity69x2** [comment]
I'm sorry I don't plan to add support for anything other than three speed fans.
