### ISSUE TITLE
Disable Unsupported Speed

### ISSUE THREAD

**Issue by gary-reyes** [finity69x2/fan-control-entity-row#9]
I have a diffuser that I am treating as a fan. It only has 3 speeds: Low, High, and Off. Could there be a way of hiding the unsupporting ones?
 Either
1) Looking at the supported modes and just not show the button
2) Have the user specify the button to hide.

**Comment by finity69x2** [comment]
No, sorry. there's no way to do that and I don't plan on adding that capability.

**Comment by sjthespian** [comment]
I know this was closed, but I'm another user who could use this functionality. I have a fan that only supports two speeds -- low and high (technically three, since "off" is a speed).

I'm faking it for now, using:
```
        customMedText: ""
```
